### ISSUE TITLE
example projects?

### ISSUE THREAD

**Issue by kylewolfe** [luxengine/lux#19]
Any plans for existing projects that can listed in the readme or maybe super minimal examples created?

Thanks,
Kyle

**Comment by hydroflame** [comment]
Yeah at some point ill do all the classics (pong, sokoban, tetris) and refractor the API as I find the cleanest way to present it all

**Comment by kylewolfe** [comment]
I was hoping to see bullet in action :)

**Comment by hydroflame** [comment]
Bullet or tornago ?

**Comment by kylewolfe** [comment]
Preferably a pure Go implementation, I would think.

**Comment by hydroflame** [comment]
there are still some bugs in the go physics engine but we're gonna get there
