### ISSUE TITLE
go get broken

### ISSUE THREAD

**Issue by kylewolfe** [luxengine/lux#2]
```
go get github.com/luxengine/lux
package luxengine.net/lux/utils: unrecognized import path "luxengine.net/lux/utils"
```

**Comment by hydroflame** [comment]
That's interresting, I have a website so you're supposed to get it via `go get luxengine.net/lux` but yeah that does break go getting from github.com

**Comment by kylewolfe** [comment]
I believe that "go get luxengine.net/lux" also fails.

**Comment by hydroflame** [comment]
Can you print your error, I just did a clean `go get` without errors

**Comment by hydroflame** [comment]
So I changed everything to use github.com/luxengine instead of luxengine.net, I'd rather that the github works. If you still cant go get it, send your error message, if not close this issue

**Comment by kylewolfe** [comment]
Both are now working fine, thanks.
