### ISSUE TITLE
Move shaders away from sources

### ISSUE THREAD

**Issue by wingrime** [luxengine/lux#21]
Anyway it sucks see shaders embedded in code.

**Comment by hydroflame** [comment]
uh, which ones, i agree that most of the shaders in hardcoded.go should probably go, but the FXAA shader and the GBuffer shaders should stay hardcoded, because i dont want to need to have a specific file setup for this to work.

**Comment by wingrime** [comment]
Uh.... Just make them in a separete go files then, don't mix glsl an go code.
