### ISSUE TITLE
Rewrite the README for the new repostory layout

### ISSUE THREAD

**Issue by sg3des** [luxengine/lux#44]
i'm understand, project in development state, but enough to break the basics :) ... 

```
go get github.com/luxengine/lux 
can't load package: package github.com/luxengine/lux: no buildable Go source files...
```
ok, look repository... main package **lux** relocated to... internal directory **render**, what? why? okay, you know better.

try another way:
```
go get github.com/luxengine/lux/... 
# cd .; git clone https://github.com/hydroflame/isitdoneyet 
[...]
```
https://github.com/hydroflame/isitdoneyet  - this is your private package, right? 

how now get project? thx ^^  

P.S. package *lux* is loaded correctly, but you should to do something with an error message, and update README

**Comment by hydroflame** [comment]
Yeah I did, needed to reorganised things a bit (also cleaned a LOT of smaller repos)

Give me the link to your project and I'll fix what I broke for you :)

**Comment by sg3des** [comment]
> P.S. package lux is loaded correctly
with my project all ok, I`ve already fixed changed paths in import.
I mean, that **Install** section in README is incorrect.

**Comment by sg3des** [comment]
hey, nice fix ^^ !
Why you just not rewrite: 
1) `go get github.com/luxengine/lux` -> `go get github.com/luxengine/lux/render`
OR 
2) remove `https://github.com/luxengine/lux/tree/master/geo/internal/stresstests/quickhull` 
then will be possible write - `go get github.com/luxengine/lux/...`

**Comment by hydroflame** [comment]
I fixed the stresstest

**Comment by hydroflame** [comment]
No longer fails to go get
