### ISSUE TITLE
Find and implement a neat transform class

### ISSUE THREAD

**Issue by hydroflame** [luxengine/lux#45]

**Comment by sg3des** [comment]
Hello again. What you mean on "neat transform class"? 
...again want to break backward compatibility?(joke). ^^

**Comment by hydroflame** [comment]
So transforms convert from one coordinate system to another, I want to find a transform representation that would do well with tornago as well as lux (render)

eg. ODE (the physics engine) uses 

    struct dxPosR {
        dVector3 pos;
        dMatrix3 R;
    };

I'm working on this idea https://github.com/luxengine/lux/blob/master/glm/transform.go

So i gotta look at many options and figure out which one is the best fit for all this

**Comment by sg3des** [comment]
It is right, transfer position, rotation etc. of objects from physics engine to gl world - is serious problem.
Also worth considering the interaction with 2D physics engine(with 3d gl).

**Comment by hydroflame** [comment]
Turns out ODE, bullet and "Game physics engine" (a book I'm reading) all have the same representation for transforms.
